packages:
- '.'
resolver: lts-16.11
extra-deps:
- github: composewell/streamly
  commit: 9fefed37d5da5aa103f93ded65b1335903651e26
- github: composewell/fusion-plugin
  commit: 1ad15ebf56a91ec967c48f7e5620f74131a947ab
nix:
  enable: true
  packages: [gmp]
